### ISSUE TITLE
satellite deployment cannot restart icinga2 due to missing configuration file

### ISSUE THREAD

**Issue by jofiedler** [bodsch/ansible-icinga2#26]
##### SUMMARY

ERROR! The requested handler 'restart icinga2 master' was not found in either the main handlers list nor in the listening handlers list

Check on satellite host:
icinga2 daemon -C
[2021-03-08 15:53:52 +0100] information/cli: Icinga application loader (version: 2.12.3)
[2021-03-08 15:53:52 +0100] information/cli: Loading configuration file(s).
[2021-03-08 15:53:52 +0100] critical/config: Error: Include file 'global-templates.conf' does not exist
Location: in /etc/icinga2/icinga2.conf: 5:1-5:31
/etc/icinga2/icinga2.conf(3): include "constants.conf"
/etc/icinga2/icinga2.conf(4): 
/etc/icinga2/icinga2.conf(5): include "global-templates.conf"
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/etc/icinga2/icinga2.conf(6): // The zones.conf defines zones for a cluster setup
/etc/icinga2/icinga2.conf(7): include "zones.conf"

[2021-03-08 15:53:52 +0100] critical/cli: Config validation failed. Re-run with 'icinga2 daemon -C' after fixing the config.
##### STEPS TO REPRODUCE

```yaml
- hosts: icinga2_agents
  gather_facts: true
  become: true
  roles:
    - role: monitoring-plugins-role
    - role: icinga2-role
  tags: icinga-agents

```

##### EXPECTED RESULTS

```paste below

```

##### ACTUAL RESULTS

```paste below

```

##### ENVIRONMENT

centos 8
